PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ncv: <http://n2t.net/ark:/39333/ncg/vocab#>

# county that Choggy Butte Mountain is in
SELECT ?county_name WHERE {
	?uri skos:prefLabel "Choggy Butte Mountain" ;
		 ncv:county ?county .
  	?county skos:prefLabel ?county_name . # query the label of the county instead of the URI
}
