PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX nct: <http://n2t.net/ark:/39333/ncg/type#>
PREFIX ncv: <http://n2t.net/ark:/39333/ncg/vocab#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# creeks in Orange County
SELECT distinct ?uri ?name
WHERE {
  ?uri dcterms:type ?type ;  # extract all the types of places 
       skos:prefLabel ?name. # extract the matching labels (required by the final result)
  filter(?type = nct:creek) # find the creek place
  
  ?uri ncv:county ?county . # extract all the counties
  ?county skos:prefLabel ?countyname . # find the matching labels of counties
  filter(regex(?countyname,"Orange County", "i")) # find the Orange County
}
order by ?name