PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

# swamps in NC
SELECT ?swamp ?swampLabel WHERE {
?swamp wdt:P31 wd:Q166735 ;
       wdt:P131* wd:Q1454 .
SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
order by ?swampLabel ?swamp